### ISSUE TITLE
Which URL should i configure at aggregator side?

### ISSUE THREAD

**Issue by bwanakweli4ever** [dsmagicug/rapidpro-external-ussd-channel#22]
HI between Rapidpro Received URL and  generated  https://domain.com/adaptor/send-url which one should configure with aggregator ?

**Comment by ekeeya** [comment]
Hi @bwanakweli4ever ,

At the aggregator side please use `/adaptor/call-back`  
You want requests from the aggregator to be  hitting the [this class.](https://github.com/dsmagicug/rapidpro-external-ussd-channel/blob/b91a9a400f16d688cd58711b2ffec297837b770b/api/views.py#L84)

Thank you
Let me know if/when you succeed.

**Comment by bwanakweli4ever** [comment]
I really tried but still no luck , i have both rapidpro instance and external ussd channel running on production server 
in most cases i get 
{
    "responseString": "External Application error",
    "action": "end"
}
i have tested with AT USSD but still get it moving , please share more guide especially on Africastalking USSD
@ekeeya is it possible to get in touch so that you can help me to get it working?

**Comment by ekeeya** [comment]
Hello @bwanakweli4ever, It's alright with me let's get in touch so I can assist with the setup.
Let's organise for Monday.
Mail me on ekeeya@ds.co.ug for further interactions.
